# This is a simple Azure configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/azure_ci/

# Choose a agent virtual image
pool:
  vmImage: ubuntu-16.04

steps:
- script: |
    mkdir -p ~/.local/bin
    curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  displayName: Install Stack
- script: |
    sudo apt-get update &&
    sudo apt-get -y install postgresql libpq-dev
  displayName: Install postgresql

- script: |
    export PATH=$HOME/.local/bin:$PATH
    stack --no-terminal --install-ghc test --only-dependencies
  displayName: Build Dependencies
- script: |
    export PATH=$HOME/.local/bin:$PATH
    # Build the package, its tests, and its docs and run the tests
    stack test
  displayName: Test Package
